name: Build and cache

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request: {}

defaults:
  run:
    shell: bash --noprofile --norc -eufo pipefail {0}

jobs:
  build:
    name: Build and cache
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - uses: DeterminateSystems/nix-installer-action@v6
        name: Setup nix

      - name: Magic nix cache setup
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build dependencies
        run: |
          nix build -L ".#default.vendorEnv"

      - name: Build executable
        run: |
          nix build -L
