name: Build and cache

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request: {}

defaults:
  run:
    shell: bash --noprofile --norc -eufo pipefail {0}

jobs:
  build:
    name: Build and cache ${{ matrix.build_pkg }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        build_pkg: [aarch64-linux]

    env:
      BUILD_PKG: ${{ matrix.build_pkg }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: DeterminateSystems/nix-installer-action@v17
        name: Setup nix

      - name: Cachix setup
        uses: cachix/cachix-action@v15
        with:
          name: "${{ vars.CACHIX_CACHE_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build dependencies
        run: |
          nix build -L ".#${BUILD_PKG?}.vendorEnv"

      - name: Build executable
        run: |
          nix build -L ".#${BUILD_PKG?}"
