name: Build and cache

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request: {}

defaults:
  run:
    shell: bash --noprofile --norc -eufo pipefail {0}

jobs:
  build:
    name: Build and cache ${{ matrix.build_pkg }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        build_pkg: [default]

    env:
      BUILD_PKG: ${{ matrix.build_pkg }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: DeterminateSystems/nix-installer-action@v6
        name: Setup nix

      - name: Magic nix cache setup
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build dependencies
        run: |
          nix build -L ".#${BUILD_PKG?}.vendorEnv"

      - name: Build executable
        run: |
          nix build -L ".#${BUILD_PKG?}"
